config/routes.rb
Rails.application.routes.draw do
  resources :specialties
  get 'admin' => 'admin#index'
  get 'disciplines/dsearch'
  get 'groups/dsearch'
  get 'disciplines/ddsearch'
  get 'groups/groupsearch'
  get 'disciplines/dddsearch'
  get 'disciplines/find_semester'
  get 'teaching_materials/tsearch'
  get 'teaching_materials/ttsearch'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  root 'client#index', as: 'client_index'
  resources :teaching_materials
  resources :disciplines
  resources :groups
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end




# call me by +375444721613 if you read it, i wanna know who are you   !!!!!!!!!!!!!!!!!!!!!!!!!!!

app/models/discipline.rb
class Discipline < ApplicationRecord
  self.primary_key = 'discipline'
  has_and_belongs_to_many :specialty
  has_many :teaching_materials
  validates :discipline, :course, :specialty_id, presence: true
  validates :discipline, uniqueness: true
end

app/controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController
  skip_before_action :authorize, only: [:show, :index, :dsearch, :ddsearch, :dddsearch, :find_semester]
  before_action :set_discipline, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_discipline

  # GET /disciplines
  # GET /disciplines.json
  def index
    @disciplines = Discipline.all
  end

  # GET /disciplines/1
  # GET /disciplines/1.json
  def show
  end

  # link from client.html by group name
  #def dsearch
  #  @d = params[:group_id]
   # if Discipline.where(group_id: @d).count > 0
    #  @disciplines = Discipline.where(group_id: @d)
    #else
     # redirect_to client_index_path, notice: 'Дисциплины группы ' + @d + ' не найдены.'
    #end
  #end

  # link from groups.html by group name
  def dddsearch
    @g = params[:group_id]
    @ddd = params[:specialty_id]
    if Discipline.where(specialty_id: @ddd).count > 0
      @disciplines = Discipline.where(specialty_id: @ddd)
    end
  end

  # search in disciplines by discipline name
  def ddsearch
    @dd = params[:discipline]
    if Discipline.where(discipline: @dd).count > 0
      @disciplines = Discipline.where(discipline: @dd)
    else
      redirect_to disciplines_path, notice: 'Дисциплина: ' + @dd + ' не найдена.'
    end
  end

  def find_semester
    @semester = params[:semester]
    @gr = params[:group_id]
    @disciplines = Discipline.where(semester: @semester, group_id: @gr)
  end

  # GET /disciplines/new
  def new
    @discipline = Discipline.new
  end

  # GET /disciplines/1/edit
  def edit
  end

  # POST /disciplines
  # POST /disciplines.json
  def create
    @discipline = Discipline.new(discipline_params)

    respond_to do |format|
      if @discipline.save
        format.html { redirect_to @discipline, notice: 'Дисциплина: ' + @discipline.discipline + ' успешно создана.' }
        format.json { render :show, status: :created, location: @discipline }
      else
        format.html { render :new }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplines/1
  # PATCH/PUT /disciplines/1.json
  def update
    respond_to do |format|
      if @discipline.update(discipline_params)
        format.html { redirect_to @discipline, notice: 'Дисциплина: ' + @discipline.discipline + ' успешно обновлена.' }
        format.json { render :show, status: :ok, location: @discipline }
      else
        format.html { render :edit }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplines/1
  # DELETE /disciplines/1.json
  def destroy
    @discipline.destroy
    respond_to do |format|
      format.html { redirect_to disciplines_url, notice: 'Дисциплина: ' + @discipline.discipline + ' успешно удалена.' }
      format.json { head :no_content }
    end
  end

  private
    def invalid_discipline
      logger.error "Attempt to access invalid discipline #{params[:id]}"
      redirect_to client_index_url, notice: 'Неверная дисциплина.'
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_discipline
      @discipline = Discipline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discipline_params
      params.require(:discipline).permit(:discipline, :teacher, :course, :specialty_id)
    end
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/views/disciplines/_form.html.erb
<%= form_with(model: discipline, local: true) do |form| %>
  <% if discipline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discipline.errors.count, "error") %> prohibited this discipline from being saved:</h2>

      <ul>
      <% discipline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <fieldset style="border-color: #97240a;">
  <div class="field">
    <%= form.label :Дисциплина %>
    <%= form.text_field :discipline, id: :discipline_discipline, class: 'edit_input' %>
  </div>

  <div class="field">
    <%= form.label :Преподаватель %>
    <%= form.text_field :teacher, id: :discipline_teacher, class: 'edit_input' %>
  </div>

  <div class="field">
    <%= form.label :Курс %>
    <%= form.text_field :course, id: :discipline_course, class: 'edit_input' %>
  </div>

  <div class="field">
    <%= form.label :Специальность %>
    <%= form.text_field :specialty_id, id: :discipline_specialty_id, class: 'edit_input' %>
  </div>

  <div class="field">
    <%= submit_tag "Сохранить", class: 'edit_button' %>
  </div>
    </fieldset>
<% end %>

app/views/disciplines/dddsearch.html.erb
<div class="main_group">
  <h1 class="hh1">Список дисциплин группы: <%= @g %></h1>


<table>
  <% if Discipline.where(specialty_id: @ddd).count > 0 %>
  <% @disciplines.each do |discipline| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td class="list_description">
            <a href="<%= teaching_materials_tsearch_path(:discipline_id => discipline.discipline) %>"><dt>
              <%= discipline.discipline %>
            </dt></a>
        </td>
        <td class="descript">
            <dd>
              Преподаватель: <%= truncate(strip_tags(discipline.teacher), length: 80) %>
            </dd>
            <dd>
              Курс: <%= truncate(strip_tags(discipline.course), length: 80) %>
            </dd>
          <dd>
            Специальность: <%= truncate(strip_tags(discipline.specialty_id), length: 80) %>
          </dd>
        </td>
        <% if session[:user_id] %>
        <td class="list_action">
          <%= link_to 'Изменить', edit_discipline_path(discipline) %><br/>
          <%= link_to 'Удалить', discipline, method: :delete, data: { confirm: 'Вы уверены?' } %>
        </td>
        <% end %>
      </tr>
  <% end %>
      <% end %>
</table>


<br>

  <% if session[:user_id] %>
      <%= link_to 'Добавить дисциплину', new_discipline_path %>
  <% end %>
</div>

app/views/disciplines/ddsearch.html.erb
<div class="main_group">
  <h1>Список дисциплин</h1>

<%= form_tag(disciplines_ddsearch_path, method: :get, class: 'search_form') do %>
      <p id="notice"><%= notice %></p>
    <%= text_field_tag :discipline, params[:discipline], class: 'search' %>
      <%= submit_tag "Найти", class: 'button' %>
<% end %>

<table>
  <% @disciplines.each do |discipline| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td class="list_description">
            <a href="<%= teaching_materials_tsearch_path(:discipline_id => discipline.discipline) %>"><dt>
              <%= discipline.discipline %>
            </dt></a>
        </td>
        <td class="descript">
            <dd>
              Преподаватель: <%= truncate(strip_tags(discipline.teacher), length: 80) %>
            </dd>
            <dd>
              Семестр: <%= truncate(strip_tags(discipline.semester), length: 80) %>
            </dd>
          <dd>
            Группа: <%= truncate(strip_tags(discipline.group_id), length: 80) %>
          </dd>
        </td>
        <% if session[:user_id] %>
        <td class="list_action">
          <%= link_to 'Изменить', edit_discipline_path(discipline) %><br/>
          <%= link_to 'Удалить', discipline, method: :delete, data: { confirm: 'Вы уверены?' } %>
        </td>
        <% end %>
      </tr>
  <% end %>
</table>

<br>
  <% if session[:user_id] %>
      <%= link_to 'Добавить дисциплину', new_discipline_path %>
  <% end %>
</div>

app/views/disciplines/dsearch.html.erb
<!--<div id="sem_table">
  <table>
    <tr>
      <td><a href="<%= disciplines_find_semester_path(:semester => 1, :group_id => @d) %>">1</a></td>
      <td><a href="<%= disciplines_find_semester_path(:semester => 2) %>">2</a></td>
    </tr>
    <tr>
      <td><a href="<%= disciplines_find_semester_path(:semester => 3) %>">3</a></td>
      <td><a href="<%= disciplines_find_semester_path(:semester => 4) %>">4</a></td>
    </tr>
    <tr>
      <td><a href="<%= disciplines_find_semester_path(:semester => 5) %>">5</a></td>
      <td><a href="<%= disciplines_find_semester_path(:semester => 6) %>">6</a></td>
    </tr>
    <tr>
      <td><a href="<%= disciplines_find_semester_path(:semester => 7, :group_id => @d) %>">7</a></td>
      <td><a href="<%= disciplines_find_semester_path(:semester => 8) %>">8</a></td>
    </tr>
  </table>
</div>
-->
<div class="main_group">
  <h1 class="hh1">Список дисциплин группы: <%= @d %></h1>

<table>
  <% if Discipline.where(group_id: @d).count > 0 %>
  <% @disciplines.each do |discipline| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td class="list_description">
            <a href="<%= teaching_materials_tsearch_path(:discipline_id => discipline.discipline) %>"><dt>
              <%= discipline.discipline %>
            </dt></a>
        </td>
        <td class="descript">
            <dd>
              Преподаватель: <%= truncate(strip_tags(discipline.teacher), length: 80) %>
            </dd>
            <dd>
              Семестр: <%= truncate(strip_tags(discipline.semester), length: 80) %>
            </dd>
          <dd>
            Группа: <%= truncate(strip_tags(discipline.group_id), length: 80) %>
          </dd>
        </td>
        <% if session[:user_id] %>
        <td class="list_action">
          <%= link_to 'Изменить', edit_discipline_path(discipline) %><br/>
          <%= link_to 'Удалить', discipline, method: :delete, data: { confirm: 'Вы уверены?' } %>
        </td>
        <% end %>
      </tr>
  <% end %>
      <% end %>
</table>


<br>

  <% if session[:user_id] %>
      <%= link_to 'Добавить дисциплину', new_discipline_path %>
  <% end %>
</div>

app/views/disciplines/edit.html.erb
<div class="edit_form">
  <legend style="color: #97240a; font-size: 24px;">Изменение дисциплины</legend>
  <div class="edit">
<%= render 'form', discipline: @discipline %>

<%= link_to 'Показать', @discipline %> |
<%= link_to 'Назад', :back %>
  </div>
</div>

app/views/disciplines/find_semester.html.erb
<div class="main_group">
  <h1>Список дисциплин</h1>

  <%= form_tag(disciplines_ddsearch_path, method: :get, class: 'search_form') do %>
      <p id="notice"><%= notice %></p>
      <%= text_field_tag :discipline, params[:discipline], class: 'search' %>
      <%= submit_tag "Найти", class: 'button' %>
  <% end %>

  <table>
    <% @disciplines.each do |discipline| %>
        <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
          <td class="list_description">
            <a href="<%= teaching_materials_tsearch_path(:discipline_id => discipline.discipline) %>"><dt>
              <%= discipline.discipline %>
            </dt></a>
          </td>
          <td class="descript">
            <dd>
              Преподаватель: <%= truncate(strip_tags(discipline.teacher), length: 80) %>
            </dd>
            <dd>
              Семестр: <%= truncate(strip_tags(discipline.semester), length: 80) %>
            </dd>
            <dd>
              Группа: <%= truncate(strip_tags(discipline.group_id), length: 80) %>
            </dd>
          </td>
          <% if session[:user_id] %>
              <td class="list_action">
                <%= link_to 'Изменить', edit_discipline_path(discipline) %><br/>
                <%= link_to 'Удалить', discipline, method: :delete, data: { confirm: 'Вы уверены?' } %>
              </td>
          <% end %>
        </tr>
    <% end %>
  </table>

  <br>
  <% if session[:user_id] %>
      <%= link_to 'Добавить дисциплину', new_discipline_path %>
  <% end %>
</div>

app/views/disciplines/index.html.erb
<div class="main_group">
  <h1>Список дисциплин</h1>

<%= form_tag(disciplines_ddsearch_path, method: :get, class: 'search_form') do %>
    <p id="notice"><%= notice %></p>
    <%= text_field_tag :discipline, params[:discipline], class: 'search' %>
      <%= submit_tag "Найти", class: 'button' %>
<% end %>

<table>
  <% @disciplines.each do |discipline| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td class="list_description">
            <a href="<%= teaching_materials_tsearch_path(:discipline_id => discipline.discipline) %>"><dt>
              <%= discipline.discipline %>
            </dt></a>
        </td>
        <td class="descript">
            <dd>
              Преподаватель: <%= truncate(strip_tags(discipline.teacher), length: 80) %>
            </dd>
            <dd>
          Курс: <%= truncate(strip_tags(discipline.course), length: 80) %>
        </dd>
          <dd>
            Специальность: <%= truncate(strip_tags(discipline.specialty_id), length: 80) %>
          </dd>
        </td>
        <% if session[:user_id] %>
        <td class="list_action">
          <%= link_to 'Изменить', edit_discipline_path(discipline) %><br/>
          <%= link_to 'Удалить', discipline, method: :delete, data: { confirm: 'Вы уверены?' } %>
        </td>
        <% end %>
      </tr>
  <% end %>
</table>

<br>
  <% if session[:user_id] %>
<%= link_to 'Добавить дисциплину', new_discipline_path %>
  <% end %>
</div>

app/views/disciplines/new.html.erb
<div class="edit_form">
  <legend style="color: #97240a; font-size: 24px;">Новая дисциплина</legend>

  <div class="edit">

<%= render 'form', discipline: @discipline %>

<%= link_to 'Назад', :back %>

  </div>
</div>

app/views/disciplines/show.html.erb
<div class="show_form">
<h2 id="notice"><%= notice %></h2>

<p>
  <strong>Название дисциплины:</strong>
  <%= @discipline.discipline %>
</p>

<p>
  <strong>Преподаватель:</strong>
  <%= @discipline.teacher %>
</p>

<p>
  <strong>Курс:</strong>
  <%= @discipline.course %>
</p>

  <p>
    <strong>Специальность:</strong>
    <%= @discipline.specialty_id %>
  </p>

<%= link_to 'Изменить', edit_discipline_path(@discipline) %> |
<%= link_to 'В меню', disciplines_path %>
</div>