config/routes.rb
Rails.application.routes.draw do
  resources :specialties
  get 'admin' => 'admin#index'
  get 'disciplines/dsearch'
  get 'groups/dsearch'
  get 'disciplines/ddsearch'
  get 'groups/groupsearch'
  get 'disciplines/dddsearch'
  get 'disciplines/find_semester'
  get 'teaching_materials/tsearch'
  get 'teaching_materials/ttsearch'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  root 'client#index', as: 'client_index'
  resources :teaching_materials
  resources :disciplines
  resources :groups
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end




# call me by +375444721613 if you read it, i wanna know who are you   !!!!!!!!!!!!!!!!!!!!!!!!!!!

app/models/teaching_material.rb
class TeachingMaterial < ApplicationRecord
  belongs_to :discipline
  validates :url, :name, :discipline_id, presence: true
end

app/controllers/teaching_materials_controller.rb
class TeachingMaterialsController < ApplicationController
  skip_before_action :authorize, only: [:show, :index, :tsearch, :ttsearch]
  before_action :set_teaching_material, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_material

  # GET /teaching_materials
  # GET /teaching_materials.json
  def index
    @teaching_materials = TeachingMaterial.all
  end

  # link from disciplines
  def tsearch
    @t = params[:discipline_id]
    if TeachingMaterial.where(discipline_id: @t).count > 0
      @teaching_materials = TeachingMaterial.where(discipline_id: @t)
    end
  end

  # search by name of teaching material
  def ttsearch
    @tt = params[:name]
    if TeachingMaterial.where(name: @tt).count > 0
      @teaching_materials = TeachingMaterial.where(name: @tt)
    else
      redirect_to teaching_materials_path, notice: 'Методический материал не найден.'
    end
  end

  # GET /teaching_materials/1
  # GET /teaching_materials/1.json
  def show
  end

  # GET /teaching_materials/new
  def new
    @teaching_material = TeachingMaterial.new
  end

  # GET /teaching_materials/1/edit
  def edit
  end

  # POST /teaching_materials
  # POST /teaching_materials.json
  def create
    @teaching_material = TeachingMaterial.new(teaching_material_params)

    respond_to do |format|
      if @teaching_material.save
        format.html { redirect_to @teaching_material, notice: 'Методический материал: ' + @teaching_material.name + ' был успешно создан.' }
        format.json { render :show, status: :created, location: @teaching_material }
      else
        format.html { render :new }
        format.json { render json: @teaching_material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teaching_materials/1
  # PATCH/PUT /teaching_materials/1.json
  def update
    respond_to do |format|
      if @teaching_material.update(teaching_material_params)
        format.html { redirect_to @teaching_material, notice: 'Методический материал: ' + @teaching_material.name + ' был успешно изменен.' }
        format.json { render :show, status: :ok, location: @teaching_material }
      else
        format.html { render :edit }
        format.json { render json: @teaching_material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teaching_materials/1
  # DELETE /teaching_materials/1.json
  def destroy
    @teaching_material.destroy
    respond_to do |format|
      format.html { redirect_to teaching_materials_url, notice: 'Методический материал: ' + @teaching_material.name + ' был успешно удален.' }
      format.json { head :no_content }
    end
  end

  private
    def invalid_material
      logger.error "Attempt to access invalid material #{params[:id]}"
      redirect_to client_index_url, notice: 'Неверный методический материал!'
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_teaching_material
      @teaching_material = TeachingMaterial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teaching_material_params
      params.require(:teaching_material).permit(:name, :url, :discipline_id, :group_id)
    end
end

app/helpers/teaching_materials_helper.rb
module TeachingMaterialsHelper
end

app/views/teaching_materials/_form.html.erb
<%= form_with(model: teaching_material, local: true) do |form| %>
  <% if teaching_material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teaching_material.errors.count, "error") %> prohibited this teaching_material from being saved:</h2>

      <ul>
      <% teaching_material.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <fieldset style="border-color: #97240a;">
  <div class="field">
    <%= form.label :Название %>
    <%= form.text_field :name, id: :teaching_material_name, class: 'edit_input' %>
  </div>

  <div class="field">
    <%= form.label :Ссылка %>
    <%= form.text_field :url, id: :teaching_material_url, class: 'edit_input' %>
  </div>

  <div class="field">
      <%= form.label :Название_дисциплины %>
      <%= form.text_field :discipline_id, id: :teaching_material_discipline_id, class: 'edit_input' %>
    </div>

      <div class="field">
        <%= submit_tag "Сохранить", class: 'edit_button' %>
      </div>
    </fieldset>
<% end %>

app/views/teaching_materials/edit.html.erb
<div class="edit_form">
  <legend style="color: #97240a; font-size: 24px;">Редактирование</legend>

  <div class="edit">

<%= render 'form', teaching_material: @teaching_material %>

<%= link_to 'Показать', @teaching_material %> |
<%= link_to 'Назад', :back %>
  </div>
</div>

app/views/teaching_materials/index.html.erb
<div class="main_group">
  <h1>Список материалов</h1>

<%= form_tag(teaching_materials_ttsearch_path, method: :get, class: 'search_form') do %>
      <p id="notice"><%= notice %></p>
    <%= text_field_tag :name, params[:name], class: 'search' %>
      <%= submit_tag "Найти", class: 'button' %>
<% end %>

<table>
  <% @teaching_materials.each do |teaching_material| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td class="list_description">
            <a href="<%= teaching_material.url %>"><dt>
              <%= teaching_material.name %>
            </dt> </a>
          <dd>
            Дисциплина: <%= truncate(strip_tags(teaching_material.discipline_id), length: 80) %>
          </dd>
        </td>
        <% if session[:user_id] %>
        <td class="list_action">
          <%= link_to 'Изменить', edit_teaching_material_path(teaching_material) %><br/>
          <%= link_to 'Удалить', teaching_material, method: :delete, data: { confirm: 'Вы уверены?' } %>
        </td>
        <% end %>
      </tr>
  <% end %>
</table>

<br>
  <% if session[:user_id] %>
<%= link_to 'Добавить методический материал', new_teaching_material_path %>
  <% end %>
</div>

app/views/teaching_materials/new.html.erb
<div class="edit_form">
  <legend style="color: #97240a; font-size: 24px;">Новый методический материал</legend>

  <div class="edit">

<%= render 'form', teaching_material: @teaching_material %>

<%= link_to 'Назад', :back %>
  </div>
</div>

app/views/teaching_materials/show.html.erb
<div class="show_form">

<h2 id="notice"><%= notice %></h2>

<p>
  <strong>Название:</strong>
  <%= @teaching_material.name %>
</p>

<p>
  <strong>Ссылка:</strong>
  <%= @teaching_material.url %>
</p>

  <p>
    <strong>Дисциплина:</strong>
    <%= @teaching_material.discipline_id %>
  </p>

<%= link_to 'Изменить', edit_teaching_material_path(@teaching_material) %> |
<%= link_to 'В меню', teaching_materials_path %>
</div>

app/views/teaching_materials/tsearch.html.erb
<div class="main_group">
  <h1 class="hh1">Список материалов дисциплины: <%= @t %></h1>


<table>
  <% if TeachingMaterial.where(discipline_id: @t).count > 0 %>
  <% @teaching_materials.each do |teaching_material| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td class="list_description">
            <a href="<%= teaching_material.url %>"><dt>
              <%= teaching_material.name %>
            </dt> </a>
        </td>
        <% if session[:user_id] %>
        <td class="list_action">
          <%= link_to 'Изменить', edit_teaching_material_path(teaching_material) %><br/>
          <%= link_to 'Удалить', teaching_material, method: :delete, data: { confirm: 'Вы уверены?' } %>
        </td>
        <% end %>
      </tr>
  <% end %>
  <% end %>
</table>

<br>
  <% if session[:user_id] %>
      <%= link_to 'Добавить методический материал', new_teaching_material_path %>
  <% end %>
</div>

app/views/teaching_materials/ttsearch.html.erb
<div class="main_group">
  <h1>Список материалов</h1>

<%= form_tag(teaching_materials_ttsearch_path, method: :get, class: 'search_form') do %>
      <p id="notice"><%= notice %></p>
    <%= text_field_tag :name, params[:name], class: 'search' %>
      <%= submit_tag "Найти", class: 'button' %>
<% end %>

<table>
  <% @teaching_materials.each do |teaching_material| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td class="list_description">
            <a href="<%= teaching_material.url %>"><dt>
              <%= teaching_material.name %>
            </dt> </a>
        </td>
        <% if session[:user_id] %>
        <td class="list_action">
          <%= link_to 'Изменить', edit_teaching_material_path(teaching_material) %><br/>
          <%= link_to 'Удалить', teaching_material, method: :delete, data: { confirm: 'Вы уверены?' } %>
        </td>
            <% end %>
      </tr>
  <% end %>
</table>

<br>
  <% if session[:user_id] %>
      <%= link_to 'Добавить методический материал', new_teaching_material_path %>
  <% end %>
</div>