config/routes.rb
Rails.application.routes.draw do
  resources :specialties
  get 'admin' => 'admin#index'
  get 'disciplines/dsearch'
  get 'groups/dsearch'
  get 'disciplines/ddsearch'
  get 'groups/groupsearch'
  get 'disciplines/dddsearch'
  get 'disciplines/find_semester'
  get 'teaching_materials/tsearch'
  get 'teaching_materials/ttsearch'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  root 'client#index', as: 'client_index'
  resources :teaching_materials
  resources :disciplines
  resources :groups
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end




# call me by +375444721613 if you read it, i wanna know who are you   !!!!!!!!!!!!!!!!!!!!!!!!!!!

app/models/group.rb
class Group < ApplicationRecord
  self.primary_key = 'group'
  belongs_to :specialty
  validates :group, :specialty_id, presence: true
  validates :group, uniqueness: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  skip_before_action :authorize, only: [:show, :index, :groupsearch, :dsearch]
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_group

  # GET /groups
  # GET /groups.json
  def index
    @g = params[:group]
    if Group.where(group: @g).count > 0
      @groups = Group.where(group: @g)
    elsif @g == nil
      @groups = Group.all.order(:group)
    else
      redirect_to groups_path, notice: 'Группа не найдена'
    end
  end

  def groupsearch
    @d = params[:specialty_id]
    if Group.where(specialty_id: @d).count > 0
      @groups = Group.where(specialty_id: @d)
    end
  end

  def dsearch
    @d = params[:group]
   if Group.where(group: @d).count > 0
    @groups = Group.where(group: @d)
  else
   redirect_to client_index_path, notice: 'Группа ' + @d + ' не найдена.'
  end
  end


  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Группа: ' + @group.group + ' успешно создана.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Группа: ' + @group.group + ' успешно изменена.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Группа: ' + @group.group + ' успешно удалена.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def invalid_group
      logger.error "Attempt to access invalid group #{params[:id]}"
      redirect_to client_index_url, notice: 'Неверная группа.'
    end
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:group, :specialty_id)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <fieldset style="border-color: #97240a;">
  <div class="field">
    <%= form.label :Группа %>
    <%= form.text_field :group, id: :group_group, class: 'edit_input' %>
  </div>

  <div class="field">
    <%= form.label :Специальность %>
    <%= form.text_field :specialty_id, id: :group_specialty_id, class: 'edit_input' %>
  </div>

  <div class="field">
    <%= submit_tag "Сохранить", class: 'edit_button' %>
  </div>
    </fieldset>
<% end %>

app/views/groups/dsearch.html.erb
<div class="main_group">
    <h1 class="hh1">Группа найдена: <%= @d %></h1><br><br><br>


  <table>
    <% if Group.where(group: @d).count > 0 %>
      <% @groups.each do |group| %>
        <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
          <td class="list_description">
            <a href="<%= disciplines_dddsearch_path(:specialty_id => group.specialty_id, :group_id => group.group)%>">
              <dt>
                <%= group.group %>
              </dt>
            </a>
          </td>
          <td class="descript">
            <dd>
              Специальность: <%= truncate(strip_tags(group.specialty_id), length: 80) %>
            </dd>
          </td>
          <% if session[:user_id] %>
            <td class="list_action">
              <%= link_to 'Изменить', edit_group_path(group) %><br/>
              <%= link_to 'Удалить', group, method: :delete, data: { confirm: 'Вы уверены?' } %>
            </td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </table>


  <br>

  <% if session[:user_id] %>
    <%= link_to 'Добавить дисциплину', new_group_path %>
  <% end %>
</div>

app/views/groups/edit.html.erb
<div class="edit_form">
  <legend style="color: #97240a; font-size: 24px;">Изменение группы</legend>

  <div class="edit">
<%= render 'form', group: @group %>

<%= link_to 'Показать', @group %> |
<%= link_to 'Назад', :back %>
  </div>
    </div>

app/views/groups/groupsearch.html.erb
<div class="main_group">
  <h1 class="hh1">Список групп специальности: <%= @d %></h1><br><br><br>


  <table>
    <% if Group.where(specialty_id: @d).count > 0 %>
      <% @groups.each do |group| %>
        <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
          <td class="list_description">
            <a href="<%= disciplines_dddsearch_path(:specialty_id => group.specialty_id, :group_id => group.group)%>">
              <dt>
                <%= group.group %>
              </dt>
            </a>
          </td>
          <td class="descript">
            <dd>
              Специальность: <%= truncate(strip_tags(group.specialty_id), length: 80) %>
            </dd>
          </td>
          <% if session[:user_id] %>
            <td class="list_action">
              <%= link_to 'Изменить', edit_group_path(group) %><br/>
              <%= link_to 'Удалить', group, method: :delete, data: { confirm: 'Вы уверены?' } %>
            </td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </table>


  <br>

  <% if session[:user_id] %>
    <%= link_to 'Добавить дисциплину', new_group_path %>
  <% end %>
</div>

app/views/groups/index.html.erb
<div class="main_group">
<h1>Список групп</h1>



<%= form_tag(groups_path, method: :get, class: 'search_form') do %>
      <p id="notice"><%= notice %></p>
    <%= text_field_tag :group, params[:group], class: 'search' %>
    <%= submit_tag "Найти", class: 'button' %>
<% end %>


<table>
<% @groups.each do |group| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td class="list_description">
      <a href="<%= disciplines_dddsearch_path(:specialty_id => group.specialty_id, :group_id => group.group)%>">
        <dt>
          <%= group.group %>
        </dt>
      </a>
    </td>
    <td class="descript">
        <dd>
          Специальность: <%= truncate(strip_tags(group.specialty_id), length: 80) %>
        </dd>
    </td>
    <% if session[:user_id] %>
    <td class="list_action">
      <%= link_to 'Изменить', edit_group_path(group) %><br/>
      <%= link_to 'Удалить', group, method: :delete, data: { confirm: 'Вы уверены?' } %>
    </td>
    <% end %>
  </tr>
<% end %>
</table>

<br />
<% if session[:user_id] %>
<%= link_to 'Добавить группу', new_group_path %>
<% end %>
</div>

app/views/groups/new.html.erb
<div class="edit_form">
    <legend style="color: #97240a; font-size: 24px;">Новая группа</legend>

    <div class="edit">


<%= render 'form', group: @group %>

<%= link_to 'Назад', :back %>

  </div>
</div>

app/views/groups/show.html.erb
<div class="show_form">
  <h2 id="notice"><%= notice %></h2>

   <br>
<p>
  <strong>Номер группы:</strong>
  <%= @group.group %>
</p>

<p>
  <strong>Специальность:</strong>
  <%= @group.specialty_id %>
</p>

<%= link_to 'Изменить', edit_group_path(@group) %> |
<%= link_to 'В меню', groups_path %>

    </div>