config/routes.rb
Rails.application.routes.draw do
  resources :specialties
  get 'admin' => 'admin#index'
  get 'disciplines/dsearch'
  get 'groups/dsearch'
  get 'disciplines/ddsearch'
  get 'groups/groupsearch'
  get 'disciplines/dddsearch'
  get 'disciplines/find_semester'
  get 'teaching_materials/tsearch'
  get 'teaching_materials/ttsearch'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  root 'client#index', as: 'client_index'
  resources :teaching_materials
  resources :disciplines
  resources :groups
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end




# call me by +375444721613 if you read it, i wanna know who are you   !!!!!!!!!!!!!!!!!!!!!!!!!!!

app/models/specialty.rb
class Specialty < ApplicationRecord
  self.primary_key = 'specialty'
  has_and_belongs_to_many :disciplines
  has_many :groups
  validates :specialty, presence: true, uniqueness: true
end

app/controllers/specialties_controller.rb
class SpecialtiesController < ApplicationController
  before_action :set_specialty, only: [:show, :edit, :update, :destroy]

  # GET /specialties
  # GET /specialties.json
  def index
    @specialties = Specialty.all
  end

  # GET /specialties/1
  # GET /specialties/1.json
  def show
  end

  # GET /specialties/new
  def new
    @specialty = Specialty.new
  end

  # GET /specialties/1/edit
  def edit
  end

  # POST /specialties
  # POST /specialties.json
  def create
    @specialty = Specialty.new(specialty_params)

    respond_to do |format|
      if @specialty.save
        format.html { redirect_to @specialty, notice: 'Specialty was successfully created.' }
        format.json { render :show, status: :created, location: @specialty }
      else
        format.html { render :new }
        format.json { render json: @specialty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specialties/1
  # PATCH/PUT /specialties/1.json
  def update
    respond_to do |format|
      if @specialty.update(specialty_params)
        format.html { redirect_to @specialty, notice: 'Specialty was successfully updated.' }
        format.json { render :show, status: :ok, location: @specialty }
      else
        format.html { render :edit }
        format.json { render json: @specialty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specialties/1
  # DELETE /specialties/1.json
  def destroy
    @specialty.destroy
    respond_to do |format|
      format.html { redirect_to specialties_url, notice: 'Specialty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_specialty
      @specialty = Specialty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def specialty_params
      params.require(:specialty).permit(:specialty, :specialization)
    end
end

app/helpers/specialties_helper.rb
module SpecialtiesHelper
end

app/views/specialties/_form.html.erb
<%= form_with(model: specialty, local: true) do |form| %>
  <% if specialty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(specialty.errors.count, "error") %> prohibited this specialty from being saved:</h2>

      <ul>
      <% specialty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <fieldset style="border-color: #97240a;">
  <div class="field">
    <%= form.label :Специальность %>
    <%= form.text_field :specialty, id: :specialty_specialty, class: 'edit_input' %>
  </div>

  <div class="field">
    <%= form.label :Специализация %>
    <%= form.text_field :specialization, id: :specialty_specialization, class: 'edit_input' %>
  </div>

    <div class="field">
      <%= submit_tag "Сохранить", class: 'edit_button' %>
    </div>
  </fieldset>
<% end %>

app/views/specialties/edit.html.erb
<div class="edit_form">
  <legend style="color: #97240a; font-size: 24px;">Изменение специальности</legend>

  <div class="edit">

<%= render 'form', specialty: @specialty %>

<%= link_to 'Показать', @specialty %> |
<%= link_to 'Назад', specialties_path %>
</div>
</div>

app/views/specialties/index.html.erb
<div class="main_group">
  <h1>Список специальностей</h1><br><br>

<p id="notice"><%= notice %></p>
<br>
    <table>
    <% @specialties.each do |specialty| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td class="list_description">
          <a href="<%= groups_groupsearch_path(:specialty_id => specialty.specialty) %>">
            <dt>
              <%= specialty.specialty %>
            </dt>
          </a>
        </td>
        <td class="descript">
          <dd>
            Специализация: <%= truncate(strip_tags(specialty.specialization), length: 80) %>
          </dd>
        </td>
        <% if session[:user_id] %>
          <td class="list_action">
            <%= link_to 'Изменить', edit_specialty_path(specialty) %><br/>
            <%= link_to 'Удалить', specialty, method: :delete, data: { confirm: 'Вы уверены?' } %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>

  <br />
  <% if session[:user_id] %>
    <%= link_to 'Добавить специальность', new_specialty_path %>
  <% end %>
</div>

app/views/specialties/new.html.erb
<div class="edit_form">
  <legend style="color: #97240a; font-size: 24px;">Новая специальность</legend>

  <div class="edit">

<%= render 'form', specialty: @specialty %>

<%= link_to 'Назад', specialties_path %>
</div>
</div>

app/views/specialties/show.html.erb
<div class="show_form">
  <h2 id="notice"><%= notice %></h2>

  <br>

<p>
  <strong>Специальность:</strong>
  <%= @specialty.specialty %>
</p>

<p>
  <strong>Специализация:</strong>
  <%= @specialty.specialization %>
</p>

<%= link_to 'Изменить', edit_specialty_path(@specialty) %> |
<%= link_to 'Назад', specialties_path %>
</div>